---
- name: Install Dependencies
  pacman: name={{ item }}
  become: yes
  with_items:
    - base-devel
    - boost
    - cmake
    - expat
    - gmp
    - git
    - ncurses
    - sbcl
    - readline
    - zlib

