---
- name: Install Dependencies
  pacman: name={{ item }}
  become: yes
  with_items:
    - base-devel
    - boost
    - cmake
    - expat
    - gmp
    - git
    - gc
    - ncurses
    - sbcl
    - readline
    - zlib

- name: Ensure python binary
  file: src=/usr/bin/python2 dest=/usr/bin/python state=link
  become: yes
