---
- name: Checkout clasp externals from repo
  git: repo={{ externals_clasp_repo_url }}
       dest={{ externals_clasp_dir }}
       force={{ externals_clasp_force_checkout }}
       version={{ externals_clasp_version }}
       recursive=false

- name: touch local.config
  shell: touch local.config
  args:
    chdir: "{{ externals_clasp_dir }}"

- name: Make externals-clasp
  shell: "make {{ externals_clasp_target }}"
  args:
    chdir: "{{ externals_clasp_dir }}"
  environment:
    - TARGET_OS: "{{ ansible_system }}"
    - PJOBS: "{{ pjobs }}"
    - GCC_TOOLCHAIN: "{{ gcc_toolchain }}"
    - GCC_EXECUTABLE: "{{ gcc_executable }}"
    - GXX_EXECUTABLE: "{{ gxx_executable }}"
