---
- name: Checkout clasp externals from repo
  git: repo={{ externals_clasp_repo_url }}
       dest={{ externals_clasp_dir }}
       version={{ externals_clasp_version }}
       recursive=false
  tags: ["clasp-externals-checkout"]

- name: Copy local.config
  template: src=local.config.j2 dest="{{ externals_clasp_dir }}/local.config"
  tags:
    - clasp-externals-config

- name: Make externals-clasp
  shell: "make {{ externals_clasp_target }}"
  args:
    chdir: "{{ externals_clasp_dir }}"
  tags: ["clasp-externals-make"]
