---
- name: Checkout clasp externals from repo
  git: repo={{ externals_clasp_repo_url }}
       dest={{ externals_clasp_dir }}
       version={{ externals_clasp_version }}
       recursive=false

- name: Touch local.config
  file: path="{{ externals_clasp_dir }}/local.config" state=touch

- name: Make externals-clasp
  shell: "make {{ externals_clasp_target }}"
  args:
    chdir: "{{ externals_clasp_dir }}"
  environment:
    - TARGET_OS: "{{ ansible_system }}"
    - PJOBS: "{{ pjobs }}"
    - GCC_TOOLCHAIN: "{{ gcc_toolchain }}"
    - GCC_EXECUTABLE: "{{ gcc_executable }}"
    - GXX_EXECUTABLE: "{{ gxx_executable }}"
