---
- name: Install Dependencies
  apt: name={{ item }}
       state=present
  become: yes
  with_items:
    - binutils-dev
    - cmake
    - emacs
    - git
    - libboost1.60-tools-dev
    - libgmp-dev
    - autoconf
    - automake
    - libtool
    - libexpat-dev
    - libz-dev
    - libbz2-dev
    - libncurses-dev
    - libreadline-dev
    - libedit-dev
    - libgc-dev
    - sbcl
    - g++
