---
- name: Checkout Boost from source
  git: repo={{ boost_repo_url }}
       dest={{ boost_dir }}
       version={{ boost_version }}
       recursive=yes
       force=yes

- name: Bootstrap Boost
  shell: "./bootstrap.sh; ./b2 headers"
  args:
    chdir: "{{ boost_dir }}"
  become: yes

- name: Make Boost
  shell: "./b2 toolset=gcc \
            --with-filesystem --with-date_time \
            --with-serialization --with-iostreams	\
            --with-program_options --with-regex	\
            --with-system --with-mpi \
            --prefix={{ externals_clasp_dir }}/build/{{ item }} \
            --std=c++11
            link=static {{ item }} \
            -j{{ pjobs }} \
            install --ignore-site-config"
  args:
    chdir: "{{ boost_dir }}"
  become: yes
  with_items:
    - debug
    - release
